name: call reusable build

on:
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      runner: ubuntu-latest
      environment: develop
      build-command: 'echo "building branch $BRANCH"'
#      debug: true

      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "deploying version ${{ needs.build.outputs.image-version }}"
    
