name: conditions as variables

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUSH_DOCKER_IMAGE: ${{ github.event_name != 'pull_request' }}
      IS_DEPENDABOT: ${{ github.actor == 'dependabot[bot]' }}
      DO_DEBUG: inputs.debug == true && var.ALLOW_DEBUG == 'true')
      TAG: ${{ github.event.release.tag_name || github.event.inputs.version }} 
    steps:
    - name: push docker image
      if: env.PUSH_DOCKER_IMAGE == 'true'
      run: echo "pushing image $TAG"
