name: chain jobs based on result

on:
  workflow_dispatch:
      
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
    - run: echo "A"
    
  B1:
    runs-on: ubuntu-latest
    needs: A
    steps:
    - run: echo "B1" && exit -1        
  B2:
    needs: B1
    runs-on: ubuntu-latest
    steps:
    - run: echo "B2"   
  B3:
    needs: B2
    runs-on: ubuntu-latest
    if: success()
    steps:
    - run: echo "B3"   
    
  C1:
    needs: A
    runs-on: ubuntu-latest
    steps:
    - run: echo "C1"   
  C2:
    needs: C1
    runs-on: ubuntu-latest
    steps:
    - run: echo "C2"   
  C3:
    needs: C2
    runs-on: ubuntu-latest
    if: success()
    steps:
    - run: echo "C3"   
